// GENERATED by scripts/build-post-registry.ts. Do not edit by hand.
// Regenerate: `bun run build:posts`.
import type { PostMeta } from "./post-schema";
import type { ComponentType } from "react";

export interface RegistryEntry {
  meta: PostMeta;
  load: () => Promise<{ default: ComponentType }>;
}

/** Keyed by `${locale}:${slug}`. */
export const POSTS_BY_SLUG: Record<string, RegistryEntry> = {
  "fr:continuous-ai-pentesting-nis2": { meta: {"title":"Pentest continu par IA agentique : pourquoi NIS2 change la donne","description":"NIS2 impose des tests de pénétration réguliers. Le pentest classique, lent et coûteux, n'y répond plus. Voici pourquoi l'IA agentique devient inévitable.","date":"2026-04-20","author":"Yanis Grigy, CEO","tags":["NIS2","Conformité","Pentest continu"],"locale":"fr","slug":"continuous-ai-pentesting-nis2","draft":false,"readingTimeMinutes":2,"path":"/blog/continuous-ai-pentesting-nis2","hreflangPath":"/en/blog/continuous-ai-pentesting-nis2"}, load: () => import("./blog/fr/continuous-ai-pentesting-nis2.mdx") },
  "en:continuous-ai-pentesting-nis2": { meta: {"title":"Continuous AI pentesting: why NIS2 changes the game","description":"NIS2 requires regular penetration testing. The traditional pentest, slow and expensive, can't keep up. Here's why agentic AI becomes inevitable.","date":"2026-04-20","author":"Yanis Grigy, CEO","tags":["NIS2","Compliance","Continuous pentest"],"locale":"en","slug":"continuous-ai-pentesting-nis2","draft":false,"readingTimeMinutes":2,"path":"/en/blog/continuous-ai-pentesting-nis2","hreflangPath":"/blog/continuous-ai-pentesting-nis2"}, load: () => import("./blog/en/continuous-ai-pentesting-nis2.mdx") },
};

export const POSTS: PostMeta[] = Object.values(POSTS_BY_SLUG).map((e) => e.meta);

export function getPost(locale: string, slug: string): RegistryEntry | undefined {
  return POSTS_BY_SLUG[`${locale}:${slug}`];
}

export function listPosts(locale: string): PostMeta[] {
  return POSTS
    .filter((p) => p.locale === locale)
    .sort((a, b) => b.date.localeCompare(a.date));
}
